name: Release library

run-name: Release library

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.VMIPASSWORD }}
        with:
          source: "."
          target: "/var/www/dms/o2accounts/${GITHUB_REF#refs/heads/}"

      - name: Executing remote command and deploying
        uses: appleboy/ssh-action@master
        env:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.VMIPASSWORD }}
          script: |
            cd /var/www/dms/o2accounts/
            mvn clean package verify install